# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Sindi Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snapshot_release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [17, 21, 23]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build with JDK ${{matrix.java}} - ${{ matrix.os }}

    steps:
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import
          echo "${{ secrets.GPG_SECRET_KEY }}" | gpg --import --no-tty --batch --yes
        
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-java@v4
        name: Set up JDK ${{matrix.java}}
        with:
        # Modules specify the oldest java version that they support:
        # even if we build with version 21, produced jars should be compatible with
        # JVMs running the version specified in each module's maven.compiler.target property
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: snapshot_release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        # Notes:
        #  - tests already run in a separate action (main)
        run: |
          mvn -B -U --fail-at-end \
            -DskipTests -DskipITs \
            clean deploy -e

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/*-reports/TEST-*.xml'
          annotate_only: true
